# version: '3.8'
services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '192.168.1.8:9000:9000'
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=tmp
    # volumes:
    #   - $dir/data_dir:/var/lib/clickhouse 
    #   - $dir/logs:/var/log/clickhouse-server 
